from app.domain.exceptions.base import (
    AIProviderUnavailableError,
    AppointmentOutsideBusinessHoursError,
    AuthorizationError,
    ConversationCompletedError,
    ConversationLimitExceededError,
    DomainError,
    EntityAlreadyExistsError,
    EntityNotFoundError,
    InactiveAccountError,
    InvalidAppointmentStatusTransitionError,
    InvalidCredentialsError,
    InvalidTicketStatusTransitionError,
    InvalidTokenError,
    VoiceLineNotFoundError,
)

__all__ = [
    "AIProviderUnavailableError",
    "AppointmentOutsideBusinessHoursError",
    "AuthorizationError",
    "ConversationCompletedError",
    "ConversationLimitExceededError",
    "DomainError",
    "EntityAlreadyExistsError",
    "EntityNotFoundError",
    "InactiveAccountError",
    "InvalidAppointmentStatusTransitionError",
    "InvalidCredentialsError",
    "InvalidTicketStatusTransitionError",
    "InvalidTokenError",
    "VoiceLineNotFoundError",
]
