"""Application entrypoint: the FastAPI app factory.

Wires together configuration, logging, middleware, exception handlers, and
versioned routers. Kept free of any business or database logic — this file
should never grow past "assemble the pieces."
"""

from __future__ import annotations

from collections.abc import AsyncIterator
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.api.v1.router import api_router
from app.core.config import get_settings
from app.core.errors import register_exception_handlers
from app.core.middleware import (
    MaxBodySizeMiddleware,
    RateLimitMiddleware,
    RequestIDMiddleware,
    RequestLoggingMiddleware,
    SecurityHeadersMiddleware,
)
from app.core.version import APP_VERSION
from app.infrastructure.database.session import engine
from app.shared.logging.setup import configure_logging, get_logger

settings = get_settings()
configure_logging(settings)
logger = get_logger("app.lifecycle")


@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncIterator[None]:
    logger.info("app_startup", environment=settings.ENVIRONMENT, version=APP_VERSION)
    yield
    await engine.dispose()
    logger.info("app_shutdown")


def create_app() -> FastAPI:
    app = FastAPI(
        title=settings.APP_NAME,
        version=APP_VERSION,
        debug=settings.DEBUG,
        lifespan=lifespan,
    )

    # Starlette's `add_middleware()` prepends each call, so the LAST call
    # here ends up OUTERMOST and the FIRST call ends up INNERMOST (closest
    # to routing). Order (outermost -> innermost): RequestLoggingMiddleware
    # -> RequestIDMiddleware -> SecurityHeadersMiddleware ->
    # MaxBodySizeMiddleware -> RateLimitMiddleware. This keeps the original
    # two middlewares' relative order unchanged and nests the three new
    # ones inside both, so: (a) RequestIDMiddleware still wraps every new
    # middleware, meaning `request.state.request_id`/the `X-Request-ID`
    # header exist even for a request the new middlewares reject; (b)
    # RequestLoggingMiddleware still logs exactly one line per request,
    # rejected or not; (c) MaxBodySizeMiddleware runs before
    # RateLimitMiddleware so an oversized request doesn't also consume a
    # rate-limit slot before being rejected anyway.
    app.add_middleware(RateLimitMiddleware)
    app.add_middleware(MaxBodySizeMiddleware)
    app.add_middleware(SecurityHeadersMiddleware)
    app.add_middleware(RequestIDMiddleware)
    app.add_middleware(RequestLoggingMiddleware)

    register_exception_handlers(app)

    app.include_router(api_router, prefix=settings.API_V1_PREFIX)

    return app


# `fastapi_app` is the FastAPI instance itself — useful in tests that need
# `app.dependency_overrides`. It is intentionally NOT what gets served.
fastapi_app = create_app()

# CORS is applied by wrapping the finished app in a raw ASGI middleware
# rather than via `fastapi_app.add_middleware(CORSMiddleware, ...)`. Reason:
# Starlette always places its ServerErrorMiddleware (which handles our
# `@app.exception_handler(Exception)` catch-all) OUTSIDE every middleware
# added via `add_middleware()`. A CORSMiddleware added that way would never
# see responses generated by the catch-all handler, so any unhandled 500
# would arrive at the browser with no Access-Control-Allow-Origin header —
# the browser reports that as a generic network failure, hiding the real
# error from client-side error handling entirely. Wrapping the whole ASGI
# app instead makes CORS the outermost layer, so it also covers 500s.
app = CORSMiddleware(
    fastapi_app,
    allow_origins=settings.CORS_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)
