"""add_ai_brain_conversation_tables

Revision ID: 08beb0556900
Revises: ce9e819ec9a5
Create Date: 2026-07-24 16:18:23.469019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08beb0556900'
down_revision: Union[str, None] = 'ce9e819ec9a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('TEXT', name='conversation_channel', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', name='conversation_status', native_enum=False, length=20), nullable=False),
    sa.Column('caller_phone_number', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_organization_id'), 'conversations', ['organization_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('CUSTOMER', 'ASSISTANT', name='message_role', native_enum=False, length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_conversation_id'), 'conversation_messages', ['conversation_id'], unique=False)
    op.create_table('conversation_outcomes',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('classification', sa.Enum('EMERGENCY', 'NON_EMERGENCY', 'UNKNOWN', name='call_classification', native_enum=False, length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('recommended_action', sa.Enum('CREATE_EMERGENCY_TICKET', 'BOOK_APPOINTMENT', 'ANSWER_FAQ', 'ESCALATE_TO_HUMAN', 'NONE', name='recommended_action', native_enum=False, length=30), nullable=False),
    sa.Column('matched_service_id', sa.UUID(), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_phone', sa.String(length=32), nullable=True),
    sa.Column('customer_address', sa.String(length=500), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_service_id'], ['services.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversation_outcomes')
    op.drop_index(op.f('ix_conversation_messages_conversation_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_conversations_organization_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
