"""add service default duration minutes

Revision ID: bac7205a4017
Revises: a943ce983ca5
Create Date: 2026-07-25 11:20:09.933491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bac7205a4017'
down_revision: Union[str, None] = 'a943ce983ca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('default_duration_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'default_duration_minutes')
    # ### end Alembic commands ###
